services:
  otel-collector:
    image: otel/opentelemetry-collector-contrib:0.114.0
    restart: always
    command:
      - --config=/etc/otelcol-contrib/otel-collector.yml
    volumes:
      - ./otel-collector.yml:/etc/otelcol-contrib/otel-collector.yml
    ports:
    - "4317:4317" # OTLP gRPC receiver
    - "4318:4318" # OTLP http receiver
    - "55679:55679" # zpages extension
    environment:
      DD_API_KEY: ${DD_API_KEY}

  python:
    image: otel-sdk-examples-python-codeless:latest
    build:
      context: ../python/codeless
    environment:
      OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4317"
      OTEL_EXPORTER_OTLP_PROTOCOL: "grpc"
      OTEL_SERVICE_NAME: "otel-sdk-examples-python-codeless"
      OTEL_TRACES_EXPORTER: "otlp"
      OTEL_METRICS_EXPORTER: "otlp"
      OTEL_LOGS_EXPORTER: "otlp"
      OTEL_PYTHON_LOGGING_AUTO_INSTRUMENTATION_ENABLED: true
      OTEL_PYTHON_LOG_LEVEL: "info"
    ports:
      -  "8000:8000"